#devtools::install_github("datadotworld/data.world-r", build_vignettes = TRUE)

saved_cfg <- data.world::save_config("eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyLWFuZC1yLXN0dWRpbzp5aWh1bnplbGVrZSIsImlzcyI6ImNsaWVudDpyLWFuZC1yLXN0dWRpbzphZ2VudDp5aWh1bnplbGVrZTo6ZDUxYTU4MjAtNjgzOC00ZDY3LTg2ZWMtYmJhYWNhYzNmMjAyIiwiaWF0IjoxNjE0NTU1NDE1LCJyb2xlIjpbInVzZXJfYXBpX2FkbWluIiwidXNlcl9hcGlfcmVhZCIsInVzZXJfYXBpX3dyaXRlIl0sImdlbmVyYWwtcHVycG9zZSI6dHJ1ZSwic2FtbCI6e319.eQbfoRt1SW_M8wPTMcQGLt6nKh2TGl5u_WuduQNntmUcsmfN6W1Ca1pUhWWqeLJ0pjPTTTpa4F1-ZSjYK34kHA
")
data.world::set_config(saved_cfg)

